#!/usr/bin/env node
'use strict';
// Builds the oh-my-ghcp plugin for GitHub Copilot CLI from an oh-my-claudecode (OMC) checkout: OMC's own files plus
// a generated hooks/hooks.json, Copilot model ids in agents/*.md, Copilot tool names in skill/agent docs, the MCP
// server cwd, ghcp-shim.cjs (the hook adapter) and ghcp-shim.json (subagent model policy).
//
// usage: node build-overlay.cjs --omc <dir> --out <dir> [--force] [--agent-model <model>]
//          [--task-model <model> | --task-model-map opus=<model>,sonnet=<model>,haiku=<model>]
//          [--rebuild-cli --esbuild <esbuild package dir>]
//   --omc             OMC checkout at a release tag with runtime dependencies installed (npm --omit=dev)
//   --out             plugin directory to generate (copilot --plugin-dir <out>)
//   --force           replace an existing <out> generated by this script
//   --agent-model     replace Claude model aliases (opus/sonnet/haiku) in agents/*.md; default: drop the line so
//                     the agent runs on the session model
//   --task-model      pin the model of every task-tool subagent
//   --task-model-map  map OMC's Claude tier hints to Copilot models; unmapped tiers run on the session model
//   --rebuild-cli     rebuild bridge/cli.cjs from OMC's src/cli (OMC v5.6.0 shipped a bundle without `omc ralph`,
//                     Yeachan-Heo/oh-my-claudecode#4202, fixed in v5.6.1); needs --esbuild or OMC's devDependencies
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const opt = parseArgs(process.argv.slice(2), {
  values: ['omc', 'out', 'agent-model', 'task-model', 'task-model-map', 'esbuild'],
  flags: ['force', 'rebuild-cli'],
});
if (!opt.omc || !opt.out) usage('--omc and --out are required');
if (opt['task-model'] && opt['task-model-map']) usage('use either --task-model or --task-model-map');
const src = path.resolve(opt.omc);
const out = path.resolve(opt.out);
const agentModel = opt['agent-model'];
const taskModel = opt['task-model'];
const taskModelMap = opt['task-model-map'] ? parseModelMap(opt['task-model-map']) : undefined;
const rebuildCli = !!opt['rebuild-cli'];

for (const f of ['.claude-plugin/plugin.json', 'hooks/hooks.json', 'scripts/run.cjs', 'bin/oh-my-claudecode.js', 'bridge/cli.cjs']) {
  if (!fs.existsSync(path.join(src, f))) fail(`${src} is not an oh-my-claudecode checkout (missing ${f})`);
}
if (!fs.existsSync(path.join(src, 'node_modules', 'commander'))) {
  fail(`OMC runtime dependencies are missing; in ${src} run: npm ci --omit=dev --ignore-scripts && npm rebuild better-sqlite3`);
}
const within = (a, b) => { const r = path.relative(b, a); return r === '' || (!r.startsWith('..') && !path.isAbsolute(r)); };
if (within(out, src) || within(src, out)) fail('--out must be outside the OMC checkout and must not contain it');
if (fs.existsSync(out)) {
  if (!opt.force) fail(`${out} exists; pass --force to replace it`);
  if (!fs.existsSync(path.join(out, 'ghcp-shim.cjs'))) fail(`refusing to replace ${out}: not an oh-my-ghcp build (no ghcp-shim.cjs)`);
}
let esbuildDir;
if (rebuildCli) {
  esbuildDir = [opt.esbuild && path.resolve(opt.esbuild), path.join(src, 'node_modules', 'esbuild')].find((p) => p && fs.existsSync(p));
  if (!esbuildDir) fail('--rebuild-cli needs esbuild: npm install --prefix <dir> esbuild@<OMC devDependency version>, then --esbuild <dir>/node_modules/esbuild');
  if (!fs.existsSync(path.join(src, 'src', 'cli', 'index.ts'))) fail('--rebuild-cli needs OMC sources (src/cli/index.ts)');
}

// Build into a staging directory so a failed build never leaves a half-written plugin where Copilot loads it.
const stage = `${out}.tmp-${process.pid}`;
removeBuild(stage);
try {
  const summary = build(stage);
  removeBuild(out);
  fs.renameSync(stage, out);
  console.log(`${out} built from OMC ${summary.version}${summary.commit ? ' @ ' + summary.commit.slice(0, 12) : ''}: ${summary.text}`);
  for (const w of summary.warnings) console.warn(`warning: ${w}`);
} catch (e) {
  try { removeBuild(stage); } catch {}
  fail(e && e.message ? e.message : String(e));
}

function build(dst) {
  const warnings = [];
  const required = ['.claude-plugin', 'scripts', 'dist', 'skills', 'agents', 'bridge', 'bin', 'hooks'];
  const optional = ['commands', 'templates', 'assets'];
  fs.mkdirSync(dst, { recursive: true });
  for (const d of [...required, ...optional]) {
    const from = path.join(src, d);
    if (!fs.existsSync(from)) {
      if (required.includes(d)) throw new Error(`OMC checkout lacks ${d}/`);
      continue;
    }
    fs.cpSync(from, path.join(dst, d), { recursive: true });
  }
  for (const f of ['.mcp.json', 'package.json', 'LICENSE']) fs.copyFileSync(path.join(src, f), path.join(dst, f));
  // Share OMC's runtime dependencies instead of copying them (ESM ignores NODE_PATH, so they must sit in an ancestor).
  fs.symlinkSync(path.join(src, 'node_modules'), path.join(dst, 'node_modules'), process.platform === 'win32' ? 'junction' : 'dir');
  fs.copyFileSync(path.join(__dirname, 'ghcp-shim.cjs'), path.join(dst, 'ghcp-shim.cjs'));

  // Copilot starts plugin MCP servers in the plugin root, and OMC's MCP tools anchor .omc/ on the server's cwd
  // (a non-git plugin dir falls back to ~/.omc). Copilot resolves a relative "cwd" against the session's working
  // directory, so "." starts the server in the project, as Claude Code does.
  const mcpPath = path.join(dst, '.mcp.json');
  const mcp = readJson(mcpPath);
  let mcpCwdCount = 0;
  for (const server of Object.values(mcp.mcpServers || {})) if (!server.cwd) { server.cwd = '.'; mcpCwdCount++; }
  fs.writeFileSync(mcpPath, JSON.stringify(mcp, null, 2) + '\n');
  const shimCfg = taskModel ? { taskModel } : taskModelMap ? { taskModelMap } : {};
  fs.writeFileSync(path.join(dst, 'ghcp-shim.json'), JSON.stringify(shimCfg, null, 2) + '\n');

  // OMC docs name tools as Claude Code exposes them: plugin MCP tools as mcp__plugin_<plugin>_<server>__<tool> and the
  // deferred-tool loader as ToolSearch(query="select:a,b"). Copilot names them <server>-<tool> and
  // tool_search_tool(pattern). Copilot only offers tool_search_tool when tools are deferred, so a prose ToolSearch
  // instruction becomes conditional; otherwise the model is told to call a tool it does not have.
  const pluginName = readJson(path.join(dst, '.claude-plugin', 'plugin.json')).name;
  const servers = Object.keys(mcp.mcpServers || {});
  const reEsc = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  let toolNameEdits = 0;
  if (servers.length) {
    const mcpName = new RegExp(`mcp__plugin_${reEsc(pluginName)}_(${servers.map(reEsc).join('|')})__(\\w+)`, 'g');
    for (const d of ['skills', 'agents', 'commands']) {
      if (!fs.existsSync(path.join(dst, d))) continue;
      for (const rel of fs.readdirSync(path.join(dst, d), { recursive: true }).map(String).filter((f) => f.endsWith('.md'))) {
        const p = path.join(dst, d, rel);
        let n = 0;
        const text = fs.readFileSync(p, 'utf8')
          .replace(mcpName, (_, server, tool) => { n++; return `${server}-${tool}`; })
          .replace(/ToolSearch\(query="select:([^"]+)"\)/g, (_, list) => {
            n++;
            return `tool_search_tool(pattern="^(${list.split(',').map((s) => reEsc(s.trim())).join('|')})$")`;
          })
          .replace(/`ToolSearch`/g, () => {
            n++;
            return '`tool_search_tool` (only if they are missing from your tool list; Copilot CLI usually lists them directly, so then just call them)';
          });
        if (n) { fs.writeFileSync(p, text); toolNameEdits += n; }
      }
    }
  }

  // Windows: Copilot runs hook commands through PowerShell, which splits "${CLAUDE_PLUGIN_ROOT}"/scripts/run.cjs into
  // two arguments. Route every hook through the shim with a fully quoted path.
  // Copilot's timeout covers its own process spawn (1-4 s on Windows) and drops the output of late hooks, so the
  // manifest timeouts are tripled; OMC's run.cjs derives its inner timeout from them minus a cushion.
  const hooksPath = path.join(dst, 'hooks', 'hooks.json');
  const hooks = readJson(hooksPath);
  const re = /^node "\$\{CLAUDE_PLUGIN_ROOT\}"\/scripts\/run\.cjs "\$\{CLAUDE_PLUGIN_ROOT\}"\/scripts\/([\w.-]+\.mjs)(.*)$/;
  const shim = 'node "${CLAUDE_PLUGIN_ROOT}/ghcp-shim.cjs"';
  const scaled = (t) => Math.max(10, Math.ceil((Number(t) || 5) * 3));
  let hookCount = 0;
  const dropped = [];
  let subagentStart = null;
  for (const [event, entries] of Object.entries(hooks.hooks)) {
    // Copilot ignores SessionStart matchers and has no init/maintenance sources, so these would run every session.
    hooks.hooks[event] = entries.filter((entry) => {
      const keep = event !== 'SessionStart' || !entry.matcher || entry.matcher === '*';
      if (!keep) dropped.push(...entry.hooks.map((h) => `${event}[${entry.matcher}] ${(h.command.match(re) || [])[1]}`));
      return keep;
    });
    for (const entry of hooks.hooks[event]) {
      for (const h of entry.hooks) {
        const m = h.command.match(re);
        if (!m) throw new Error('unexpected OMC hook command (adapter needs an update): ' + h.command);
        h.command = `${shim} --event ${event} ./scripts/${m[1]}${m[2]}`;
        h.timeout = scaled(h.timeout);
        if (event === 'SubagentStart') {
          if (subagentStart) throw new Error('more than one SubagentStart hook; the shim synthesizes only one');
          subagentStart = { tail: ` --subagent-start ./scripts/${m[1]}${m[2]}`, timeout: h.timeout };
        }
        hookCount++;
      }
    }
  }
  // First entry per event: the host note (main session), and for a subagent's first prompt the synthesized SubagentStart.
  const note = (event, tail, timeout) => ({ matcher: '*', hooks: [{ type: 'command', command: `${shim} --event ${event} --host-note${tail}`, timeout }] });
  hooks.hooks.SessionStart = hooks.hooks.SessionStart || [];
  hooks.hooks.UserPromptSubmit = hooks.hooks.UserPromptSubmit || [];
  hooks.hooks.SessionStart.unshift(note('SessionStart', '', 10));
  hooks.hooks.UserPromptSubmit.unshift(note('UserPromptSubmit', subagentStart ? subagentStart.tail : '', subagentStart ? subagentStart.timeout : 10));
  fs.writeFileSync(hooksPath, JSON.stringify(hooks, null, 2) + '\n');

  // Copilot rejects Claude model aliases ("Model 'opus' is not available").
  const alias = /^model:[ \t]*(opus|sonnet|haiku)[ \t]*\r?\n/m;
  let agentCount = 0;
  for (const f of fs.readdirSync(path.join(dst, 'agents')).filter((n) => n.endsWith('.md'))) {
    const p = path.join(dst, 'agents', f);
    const text = fs.readFileSync(p, 'utf8');
    const end = text.indexOf('\n---', 3);
    if (!text.startsWith('---') || end < 0 || !alias.test(text.slice(0, end + 1))) continue;
    const head = text.slice(0, end + 1).replace(alias, agentModel ? `model: ${agentModel}\n` : '');
    fs.writeFileSync(p, head + text.slice(end + 1));
    agentCount++;
  }

  if (rebuildCli) {
    const esbuild = require(esbuildDir);
    // Same options as OMC's scripts/build-cli.mjs, written into the plugin instead of the checkout.
    esbuild.buildSync({
      absWorkingDir: src,
      entryPoints: ['src/cli/index.ts'],
      bundle: true,
      preserveSymlinks: true,
      platform: 'node',
      target: 'node18',
      format: 'cjs',
      outfile: path.join(dst, 'bridge', 'cli.cjs'),
      banner: { js: 'const importMetaUrl = require("url").pathToFileURL(__filename);' },
      define: { 'import.meta.url': 'importMetaUrl' },
      external: [
        'fs', 'fs/promises', 'path', 'os', 'util', 'stream', 'events',
        'buffer', 'crypto', 'http', 'https', 'url',
        'child_process', 'assert', 'module', 'net', 'tls',
        'dns', 'readline', 'tty', 'worker_threads',
        '@ast-grep/napi', 'better-sqlite3', 'jsonc-parser',
      ],
      logLevel: 'warning',
    });
  }
  if (!/\.command\(["']ralph["']\)/.test(fs.readFileSync(path.join(dst, 'bridge', 'cli.cjs'), 'utf8'))) {
    warnings.push('bridge/cli.cjs has no `omc ralph` command (stale OMC bundle, #4202); use OMC >= v5.6.1 or --rebuild-cli');
  }

  const version = readJson(path.join(src, 'package.json')).version;
  let commit;
  try { commit = execFileSync('git', ['-C', src, 'rev-parse', 'HEAD'], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim(); } catch {}
  fs.writeFileSync(path.join(dst, 'oh-my-ghcp.json'), JSON.stringify({
    omc: { version, commit },
    builtAt: new Date().toISOString(),
    options: { agentModel, taskModel, taskModelMap, rebuildCli },
  }, null, 2) + '\n');

  const text = `${hookCount} hook commands (+2 host-note), dropped ${dropped.length} [${dropped.join('; ')}], ` +
    `${agentCount} agent model aliases ${agentModel ? '-> ' + agentModel : 'dropped'}, ` +
    `task model ${taskModel || (taskModelMap ? 'map ' + JSON.stringify(taskModelMap) : 'not pinned')}, ` +
    `cli ${rebuildCli ? 'rebuilt' : 'as shipped'}, ${mcpCwdCount} MCP server cwd -> ".", ${toolNameEdits} Claude tool names in docs -> Copilot names`;
  return { version, commit, text, warnings };
}

// Removes a generated plugin dir; its node_modules link is unlinked first so OMC's shared dependencies stay intact.
function removeBuild(dir) {
  let st;
  try { st = fs.lstatSync(dir); } catch { return; }
  if (!st.isDirectory()) throw new Error(`${dir} is not a directory`);
  const nm = path.join(dir, 'node_modules');
  let link;
  try { link = fs.lstatSync(nm); } catch {}
  if (link && link.isSymbolicLink()) fs.unlinkSync(nm);
  fs.rmSync(dir, { recursive: true, force: true });
  if (!fs.existsSync(path.join(src, 'node_modules', 'commander'))) throw new Error(`OMC dependencies under ${src} were removed`);
}

function parseModelMap(s) {
  const map = {};
  for (const pair of s.split(',').map((p) => p.trim()).filter(Boolean)) {
    const [tier, model] = pair.split('=').map((p) => (p || '').trim());
    if (!/^(opus|sonnet|haiku)$/.test(tier) || !model) usage(`bad --task-model-map entry "${pair}" (expected opus|sonnet|haiku=<model>)`);
    map[tier] = model;
  }
  return map;
}

function parseArgs(list, spec) {
  const res = {};
  for (let i = 0; i < list.length; i++) {
    const m = /^--([\w-]+)(?:=(.*))?$/.exec(list[i]);
    if (!m) usage(`unexpected argument: ${list[i]}`);
    const [, name, inline] = m;
    if (spec.flags.includes(name)) { res[name] = true; continue; }
    if (!spec.values.includes(name)) usage(`unknown option --${name}`);
    const value = inline !== undefined ? inline : list[++i];
    if (value === undefined || (inline === undefined && value.startsWith('--'))) usage(`--${name} needs a value`);
    res[name] = value;
  }
  return res;
}

function readJson(p) {
  return JSON.parse(fs.readFileSync(p, 'utf8'));
}

function usage(msg) {
  console.error(`error: ${msg}\n` +
    'usage: node build-overlay.cjs --omc <dir> --out <dir> [--force] [--agent-model <model>]\n' +
    '         [--task-model <model> | --task-model-map opus=<model>,sonnet=<model>,haiku=<model>]\n' +
    '         [--rebuild-cli --esbuild <esbuild package dir>]');
  process.exit(2);
}

function fail(msg) {
  console.error(`error: ${msg}`);
  process.exit(1);
}
